name: retreat recharge
favicon: null
layout_spectrum: 0.10912025580182672
typography_spectrum: 0.27623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aeb9cb'
    - '#006e9f'
    - '#002e42'
    - '#5391b8'
    - '#07080a'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
