name: retreat recharge
favicon: null
layout_spectrum: 0.10912025580182672
typography_spectrum: 0.2955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8f8'
    - '#060709'
    - '#616765'
    - '#9d9690'
    - '#8b301b'
  brandStrength: 0.20186271518468857
  lightness: 0.6719119774643332
  saturation: 0.5120112588629127
  rhythmicContrast: 0.701123416190967
purpose: []
